# Module 1: Data validation and pre-processing technique

In [1]:
#import library packages
import numpy as n
import pandas as p

In [2]:
#Load given dataset
data = p.read_csv('UPI_FRAUD.csv')

In [3]:
import warnings
warnings.filterwarnings('ignore')

Before drop the given dataset

In [4]:
data.head()

,Merchant_id,TransactionDate,AverageAmountTransactionDay,TransactionAmount,Is_declined,TotalNumberOfDeclinesDay,isForeignTransaction,isHighRiskCountry,DailyChargebackAvgAmt,Six_MonthAvgChbkAmt,Six_MonthChbkFreq,isFradulent
0,3160040998,NaN,100.0,3000.0,N,5,Y,Y,0,0.0,0,Y
1,3160040998,NaN,100.0,4300.0,N,5,Y,Y,0,0.0,0,Y
2,3160041896,NaN,185.5,4823.0,Y,5,N,N,0,0.0,0,Y
3,3160141996,NaN,185.5,5008.5,Y,8,N,N,0,0.0,0,Y
4,3160241992,NaN,500.0,26000.0,N,0,Y,Y,800,677.2,6,Y

In [5]:
#shape
data.shape

(3075, 12)

In [6]:
data.columns

Index(['Merchant_id', 'TransactionDate', 'AverageAmountTransactionDay',
       'TransactionAmount', 'Is_declined', 'TotalNumberOfDeclinesDay',
       'isForeignTransaction', 'isHighRiskCountry', 'DailyChargebackAvgAmt',
       'Six_MonthAvgChbkAmt', 'Six_MonthChbkFreq', 'isFradulent'],
      dtype='object')

After drop the given dataset

In [7]:
del data['TransactionDate']
del data['Merchant_id']

In [8]:
df=data.dropna()

In [9]:
df.shape

(3075, 10)

In [10]:
df.describe()

,AverageAmountTransactionDay,TransactionAmount,TotalNumberOfDeclinesDay,DailyChargebackAvgAmt,Six_MonthAvgChbkAmt,Six_MonthChbkFreq
count,3075.000000,3075.000000,3075.000000,3075.000000,3075.000000,3075.000000
mean,515.026556,9876.399210,0.957398,55.737561,40.022407,0.391870
std,291.906978,10135.331016,2.192391,206.634779,155.968840,1.548479
min,4.011527,0.000000,0.000000,0.000000,0.000000,0.000000
25%,269.788047,2408.781147,0.000000,0.000000,0.000000,0.000000
50%,502.549575,6698.891856,0.000000,0.000000,0.000000,0.000000
75%,765.272803,14422.568935,0.000000,0.000000,0.000000,0.000000
max,2000.000000,108000.000000,20.000000,998.000000,998.000000,9.000000

In [11]:
df.columns

Index(['AverageAmountTransactionDay', 'TransactionAmount', 'Is_declined',
       'TotalNumberOfDeclinesDay', 'isForeignTransaction', 'isHighRiskCountry',
       'DailyChargebackAvgAmt', 'Six_MonthAvgChbkAmt', 'Six_MonthChbkFreq',
       'isFradulent'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3075 entries, 0 to 3074
Data columns (total 10 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   AverageAmountTransactionDay  3075 non-null   float64
 1   TransactionAmount            3075 non-null   float64
 2   Is_declined                  3075 non-null   object
 3   TotalNumberOfDeclinesDay     3075 non-null   int64
 4   isForeignTransaction         3075 non-null   object
 5   isHighRiskCountry            3075 non-null   object
 6   DailyChargebackAvgAmt        3075 non-null   int64
 7   Six_MonthAvgChbkAmt          3075 non-null   float64
 8   Six_MonthChbkFreq            3075 non-null   int64
 9   isFradulent                  3075 non-null   object
dtypes: float64(3), int64(3), object(4)
memory usage: 240.4+ KB

Checking duplicate value from dataframe

In [13]:
#Checking for duplicate data
df.duplicated()

0       False
1       False
2       False
3       False
4       False
        ...
3070    False
3071    False
3072    False
3073    False
3074    False
Length: 3075, dtype: bool

In [14]:
#find sum of duplicate data
sum(df.duplicated())

1

In [15]:
#Checking sum of missing values
df.isnull().sum()

AverageAmountTransactionDay    0
TransactionAmount              0
Is_declined                    0
TotalNumberOfDeclinesDay       0
isForeignTransaction           0
isHighRiskCountry              0
DailyChargebackAvgAmt          0
Six_MonthAvgChbkAmt            0
Six_MonthChbkFreq              0
isFradulent                    0
dtype: int64

In [16]:
df.isForeignTransaction.unique()

array(['Y', 'N'], dtype=object)

In [17]:
df.isFradulent.unique()

array(['Y', 'N'], dtype=object)

In [18]:
df.Is_declined.unique()

array(['N', 'Y'], dtype=object)

In [19]:
df.TransactionAmount.unique()

array([ 3000.,  4300.,  4823., ..., 20800., 12000., 36000.])

In [20]:
df.isHighRiskCountry.unique()

array(['Y', 'N'], dtype=object)

In [21]:
df.DailyChargebackAvgAmt.unique()

array([  0, 800, 900, 721, 865, 816, 986, 953, 896, 701, 877, 454, 973,
       970, 993, 967, 923, 589, 888, 618, 381, 964, 995, 959, 593, 931,
       739, 475, 982, 991, 707, 916, 577, 667, 695, 735, 835, 901, 955,
       403, 996, 954, 917, 502, 894, 833, 377, 614, 786, 939, 487, 802,
       183, 942, 985, 527, 788, 801, 878, 992, 971, 961, 876, 822, 856,
       572, 789, 795, 987, 557, 398, 943, 884, 938, 780, 940, 777, 941,
       841, 673, 956, 754, 530, 918, 730, 712, 946, 435, 914, 937, 260,
       714, 998, 718, 873, 263, 853, 859, 825, 891, 657, 948, 520, 759,
       573, 640, 957, 869, 819, 649, 862, 683, 601, 604, 889, 867, 887,
       300, 518, 711, 567, 848, 960, 978, 990, 857, 585, 806, 290, 928,
       830, 684, 274], dtype=int64)

In [22]:
p.Categorical(df['isFradulent']).describe()

            counts     freqs
categories
N             2627  0.854309
Y              448  0.145691

In [23]:
p.Categorical(df['Six_MonthAvgChbkAmt']).describe()

            counts     freqs
categories
0.0           2857  0.929106
101.0            1  0.000325
102.0            1  0.000325
111.0            1  0.000325
115.0            1  0.000325
...            ...       ...
981.0            1  0.000325
989.0            1  0.000325
992.0            1  0.000325
996.0            1  0.000325
998.0            1  0.000325

[146 rows x 2 columns]

In [24]:
p.Categorical(df['AverageAmountTransactionDay']).describe()

             counts     freqs
categories
4.011526884       1  0.000325
4.356148418       1  0.000325
5.704093201       1  0.000325
5.902675552       1  0.000325
6.309560414       1  0.000325
...             ...       ...
999.1947062       1  0.000325
1000.0           10  0.003252
1200.0            2  0.000650
1500.0            2  0.000650
2000.0            4  0.001301

[3016 rows x 2 columns]

In [25]:
df.columns

Index(['AverageAmountTransactionDay', 'TransactionAmount', 'Is_declined',
       'TotalNumberOfDeclinesDay', 'isForeignTransaction', 'isHighRiskCountry',
       'DailyChargebackAvgAmt', 'Six_MonthAvgChbkAmt', 'Six_MonthChbkFreq',
       'isFradulent'],
      dtype='object')

In [26]:
df['Six_MonthAvgChbkAmt'].value_counts()

Six_MonthAvgChbkAmt
0.0      2857
585.0      59
797.0       3
728.0       3
758.0       2
         ...
883.0       1
441.0       1
633.0       1
996.0       1
170.0       1
Name: count, Length: 146, dtype: int64

In [27]:
from sklearn.preprocessing import LabelEncoder
var_mod = ['AverageAmountTransactionDay', 'TransactionAmount', 'Is_declined',
       'TotalNumberOfDeclinesDay', 'isForeignTransaction', 'isHighRiskCountry',
       'DailyChargebackAvgAmt', 'Six_MonthAvgChbkAmt', 'Six_MonthChbkFreq',
       'isFradulent']
le = LabelEncoder()
for i in var_mod:
    df[i] = le.fit_transform(df[i]).astype(int)

In [28]:
df.isFradulent.unique()

array([1, 0])

In [29]:
df.Is_declined.unique()

array([0, 1])

In [30]:
df.isForeignTransaction.unique()

array([1, 0])

In [31]:
df.isHighRiskCountry.unique()

array([1, 0])

In [32]:
df.corr()

,AverageAmountTransactionDay,TransactionAmount,Is_declined,TotalNumberOfDeclinesDay,isForeignTransaction,isHighRiskCountry,DailyChargebackAvgAmt,Six_MonthAvgChbkAmt,Six_MonthChbkFreq,isFradulent
AverageAmountTransactionDay,1.000000,0.608271,0.047952,-0.007345,0.037603,0.010469,0.024944,0.039357,0.047975,0.012969
TransactionAmount,0.608271,1.000000,0.130207,0.211318,0.202993,0.243742,0.150085,0.175933,0.200643,0.398265
Is_declined,0.047952,0.130207,1.000000,0.086067,0.079761,0.127586,0.268632,0.397625,0.499365,0.271282
TotalNumberOfDeclinesDay,-0.007345,0.211318,0.086067,1.000000,0.237198,0.302400,0.096903,0.081698,0.088722,0.536746
isForeignTransaction,0.037603,0.202993,0.079761,0.237198,1.000000,0.489572,0.040358,0.059970,0.077083,0.478113
isHighRiskCountry,0.010469,0.243742,0.127586,0.302400,0.489572,1.000000,0.056636,0.070889,0.098241,0.639792
DailyChargebackAvgAmt,0.024944,0.150085,0.268632,0.096903,0.040358,0.056636,1.000000,0.903812,0.763734,0.340313
Six_MonthAvgChbkAmt,0.039357,0.175933,0.397625,0.081698,0.059970,0.070889,0.903812,1.000000,0.823442,0.366097
Six_MonthChbkFreq,0.047975,0.200643,0.499365,0.088722,0.077083,0.098241,0.763734,0.823442,1.000000,0.443824
isFradulent,0.012969,0.398265,0.271282,0.536746,0.478113,0.639792,0.340313,0.366097,0.443824,1.000000

After Pre-processing

In [33]:
df.head()

,AverageAmountTransactionDay,TransactionAmount,Is_declined,TotalNumberOfDeclinesDay,isForeignTransaction,isHighRiskCountry,DailyChargebackAvgAmt,Six_MonthAvgChbkAmt,Six_MonthChbkFreq,isFradulent
0,248,813,0,5,1,1,0,0,0,1
1,248,1056,0,5,1,1,0,0,0,1
2,498,1146,1,5,0,0,0,0,0,1
3,498,1178,1,8,0,0,0,0,0,1
4,1490,2777,0,0,1,1,58,92,6,1

In [34]:
df.columns

Index(['AverageAmountTransactionDay', 'TransactionAmount', 'Is_declined',
       'TotalNumberOfDeclinesDay', 'isForeignTransaction', 'isHighRiskCountry',
       'DailyChargebackAvgAmt', 'Six_MonthAvgChbkAmt', 'Six_MonthChbkFreq',
       'isFradulent'],
      dtype='object')

In [35]:
df.head(10)

,AverageAmountTransactionDay,TransactionAmount,Is_declined,TotalNumberOfDeclinesDay,isForeignTransaction,isHighRiskCountry,DailyChargebackAvgAmt,Six_MonthAvgChbkAmt,Six_MonthChbkFreq,isFradulent
0,248,813,0,5,1,1,0,0,0,1
1,248,1056,0,5,1,1,0,0,0,1
2,498,1146,1,5,0,0,0,0,0,1
3,498,1178,1,8,0,0,0,0,0,1
4,1490,2777,0,0,1,1,58,92,6,1
5,1490,2801,0,0,1,1,58,92,6,1
6,730,1946,0,0,0,0,90,40,7,1
7,498,1931,1,10,0,0,0,0,0,1
8,498,1362,1,10,0,0,0,0,0,1
9,498,1490,1,10,0,0,0,0,0,1

In [36]:
df.isnull().sum()

AverageAmountTransactionDay    0
TransactionAmount              0
Is_declined                    0
TotalNumberOfDeclinesDay       0
isForeignTransaction           0
isHighRiskCountry              0
DailyChargebackAvgAmt          0
Six_MonthAvgChbkAmt            0
Six_MonthChbkFreq              0
isFradulent                    0
dtype: int64

In [37]:
df.tail(10)

,AverageAmountTransactionDay,TransactionAmount,Is_declined,TotalNumberOfDeclinesDay,isForeignTransaction,isHighRiskCountry,DailyChargebackAvgAmt,Six_MonthAvgChbkAmt,Six_MonthChbkFreq,isFradulent
3065,651,624,0,0,0,0,0,0,0,0
3066,778,1541,0,2,0,0,0,0,0,0
3067,385,605,0,0,0,0,0,0,0,0
3068,2046,418,0,0,0,0,0,0,0,0
3069,3012,2747,1,0,1,0,50,78,7,0
3070,1490,1914,1,0,0,0,50,78,7,0
3071,2387,0,1,0,0,0,50,78,7,0
3072,2387,2583,1,0,0,0,50,78,7,0
3073,3014,2013,1,0,1,1,50,78,7,0
3074,3014,2881,1,0,1,1,50,78,7,0